version: "3.5"

services:
  db:
    image: mariadb:10.11
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: touchh_app
      MYSQL_DATABASE: touchh_db
      MYSQL_USER: touchh_user
      MYSQL_PASSWORD: touchh_user_password
    networks:
      - touchh-network

  wordpress:
    depends_on:
      - db
    build: ./
    volumes:
      - "site-data:/var/www/wp-content"
    ports:
      - "8123:80"
    environment:
      DB_HOST: db
      DB_PASSWORD: touchh_app
      DB_NAME: touchh_db
      DB_USER: touchh_user
      WORDPRESS_SITE_URL: http://localhost:8123
      FS_METHOD: direct
      # For debugging only:
      WP_DEBUG: "true"
      WP_DEBUG_DISPLAY: "true"
    networks:
      - touchh-network

volumes:
  db-data:
  site-data:

networks:
  touchh-network:
    driver: bridge